OCA/pylint-odoo

.coveragerc
pylint_odoo/checkers/modules_odoo.py
pylint_odoo/misc.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/test_module/res_users.xml

Many times we have next traceback in our customer builds projects:
```bash
2015-10-08 20:32:43,139 232 ERROR openerp_test openerp.addons.base.ir.ir_mail_server: Mail delivery failed via SMTP server 'localhost'.
error: 111
Connection refused
2015-10-08 20:32:43,139 232 ERROR openerp_test openerp.addons.mail.mail_mail: failed sending mail.mail 21
File "addons/mail/mail_mail.py", line 304, in send
context=context)
File "openerp/api.py", line 241, in wrapper
return old_api(self, *args, **kwargs)
File "openerp/addons/base/ir/ir_mail_server.py", line 503, in send_email
raise MailDeliveryException(_("Mail Delivery Failed"), msg)
MailDeliveryException: ('Mail Delivery Failed', u"Mail delivery failed via SMTP server 'localhost'.\nerror: 111\nConnection refused") …
```

[IMP] Add check 'create-user-without-reset-password'

---

pylint_odoo/misc.py
pylint_odoo/test_repo/test_module/res_users.xml

Many times we need duplicate a xml_id one with noupdate="1" and another one
with noupdate="0"
Fix OCA/maintainer-quality-tools#276

[REF] Support of 'noupdate' in check 'duplicate-xml-record-id'

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test/main.py

It don't is deprecated now but this check can be used in the future.
Then we can have this check in pylint-odoo (for use it in other projects) but we can wait to enabled in oca/MQT

[ADD] Add check 'deprecated-openerp-xml-node'

---

pylint_odoo/test/main.py

Change the test fail summary of
```
======================================================================
FAIL: test_30_disabling_errors (main.MainTest)
----------------------------------------------------------------------
File "/Users/moylop260/odoo/pylint-odoo/pylint_odoo/test/main.py", line 102, in test_30_disabling_errors
self.assertEqual(sorted(real_errors.items()), sorted(EXPECTED_ERRORS.items()))
AssertionError: Errors found 23 different to expected 22
----------------------------------------------------------------------
Ran 3 tests in 0.699s
```
to
```bash
======================================================================
FAIL: test_30_disabling_errors (main.MainTest)
---------------------------------------------------------------------- …
```

[REF] test: better way to identify check error expected

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/misc.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

This check is part of the <a href='https://github.com/OCA/pylint-odoo/issues/14'>roadmap</a> Methods that required even a translation (warning, errors...)
Many times we have warning or error exceptions and we forget to add the method translate _('mystring') in our string.
This check review all methods where a translation is required and just have a string directly by param.

[ADD] translation-required: Add check to required even a translation

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test/main.py

[IMP] Add pylint check trailing newlines in other extension files.

[IMP] Add pylint check missing newline in extra extension files.

---

pylint_odoo/misc.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

I tested the new pylint-odoo-2.0.0 of MQT here:
https://github.com/OCA/account-financial-reporting/pull/189#issuecomment-219645638
And I saw the following error:
```bash
File "pylint_odoo/misc.py", line 44, in join_node_args_kwargs
args = node.args + getattr(node, 'keywords', [])
AttributeError: 'Name' object has no attribute 'args'
```

[FIX] join_node_args_kwargs: AttributeError

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test_repo/broken_module/lib/broken_example.js

- Many external libraries of javascript are used in our odoo modules, but we can't to maintain, then should be without changes.

[REF] javascript-lint: Ignore /lib/ subfolder

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

- Verify the guideline [never-commit-the-transaction](https://github.com/oca/maintainer-tools/blob/master/CONTRIBUTING.md#never-commit-the-transaction)

[ADD] invalid-commit: Add new check invalid-commit

---

pylint_odoo/checkers/modules_odoo.py

- Message before: Duplicate id id_example1 in ir.model.access.csv file
- Message now: security/ir.model.access.csv duplicated id id_example1

[REF] duplicate-id-csv: Better message error

---

pylint_odoo/misc.py
pylint_odoo/test_repo/broken_module/model_view_odoo2.xml

The old sentence `field.values()[0]` returns the first item from `field xml` sentence in most cases it works well.
But if we have a style different like as `<field eval="1" name="perm_read"/>` we should process the second one.
Then I change to `field.attrib.get('name')` sentence to avoid future problem with styles.
Detected from: https://travis-ci.org/OCA/server-tools/jobs/132336867#L423

[FIX] duplicate-xml-fields: Support security xml style

---

pylint_odoo/augmentations/main.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/pylint_deprecated_modules/README.md
pylint_odoo/test_repo/pylint_deprecated_modules/openerp/__init__.py
pylint_odoo/test_repo/test_module/__init__.py
pylint_odoo/test_repo/test_module/osv_expression.py
tox.ini

Fix https://github.com/OCA/maintainer-quality-tools/issues/306 - `from openerp.osv import expression` is a valid import yet.
Output result example:

[IMP] deprecated-module: Add exception for openerp.osv.expression

---

.travis.yml
pylint_odoo/misc.py
pylint_odoo/test/main.py
tox.ini

- Add a profiling report of top five `pytlint_odoo` methods more time consuming or more times executed.
e.g.
- This report is useful for developers to improve performance.
- Improve performance, now show minor cProfile values:

[IMP] pylint_odoo: Enable cProfile print stats and improve performance

---

tox.ini

We are using pylint==1.4 from requirements.txt
But we are using a unreleased pylint==2.0 (master branch) from tox in order to verify future compatibility with our checks.
Just now there is a error to install master package, then we need freeze a stable sha in order to avoid flaky errors in the future.

[REF] tox: Freeze stable sha pylint20

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

```python
def my_method(self, cr, uid, ids, context=None):  # method old api v7
pass
```
Idea for v9 projects to easiest migration to v10 where the old api should be deprecated.
NOTE: This PR don't enable the check in MQT, but is required for our local process, we can discuss the enabling in MQT project.

[ADD] old-api7-method-defined: Emit message if the method defined have (self, cr, uid)

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/checkers/no_modules.py
pylint_odoo/misc.py
pylint_odoo/test_repo/broken_module/model_view_odoo2.xml

Change from
`pylint_odoo/test_repo/broken_module/`**`__init__`:1:**
[W7910(wrong-tabs-instead-of-spaces), ]  **model_view_odoo.xml:23** Use wrong tabs indentation instead of four spaces`
to `pylint_odoo/test_repo/broken_module/`**model_view_odoo.xml:23:**
[W7910(wrong-tabs-instead-of-spaces), ] **(nothing)** Use wrong tabs indentation instead of four spaces`

[REF] global refactoring: better message output and use real file and line number in non-py files

---

README.rst
pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test_repo/broken_module2/README.rst

- Fix https://github.com/OCA/pylint-odoo/issues/38
The best solution is add support for sphinx RST directives.
But we had problems from main libraries to get a parser, more info:
- https://github.com/twolfson/restructuredtext-lint/issues/29
- https://github.com/sphinx-doc/sphinx/issues/2922
Then for now we need to skip this type of errors and add a `TODO` if the issue is fixed.

[FIX] rst-syntax-error: Skip unknown directives and roles

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/misc.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/no_odoo_module/myfile.py
pylint_odoo/test_repo/test_module/__openerp__.py
pylint_odoo/test_repo/test_module/absolute_import.py
pylint_odoo/test_repo/test_module/osv_expression.py
tox.ini

Based on [external dependencies guideline](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#external-dependencies)
Inspired from https://github.com/OCA/maintainer-tools/pull/224
FYI the variable `DFLT_IMPORT_NAME_WHITELIST` was filled running this check on [odoo/odoo#master](https://github.com/odoo/odoo/tree/master)..[odoo/odoo#8.0](https://github.com/odoo/odoo/tree/8.0)
`PYTHONPATH=~/build/OCA/pylint-odoo pylint --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" -d all -e missing-import-error --load-plugins=pylint_odoo odoo/addons/* odoo/openerp/addons/* odoo odoo/openerp -rn`

[ADD] missing-import-error, missing-manifest-dependency

---

requirements.txt

When using the pylint_odoo plugin as part of the OCA's Maintainer Quality Tools it doesn't appear to be installing the isort library that pylint_odoo depends on which has meant that my linting jobs in Travis have been erroring with the following:
```
======== Testing test_pylint ========
File "/home/travis/maintainer-quality-tools/travis/test_pylint", line 173, in <module>
] + extra_params_cmd, standalone_mode=False)
File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
return self.main(*args, **kwargs)
File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 696, in main
rv = self.invoke(ctx)
File …
```

Adding isort dependency

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/checkers/no_modules.py
requirements.txt
tox.ini

Update version of dependencies:
- astroid==1.4.8
- pylint==1.6.4
- pylint-plugin-utils==0.2.4
For test use last sha:
- https://github.com/PyCQA/astroid/commit/9979615
- https://github.com/PyCQA/pylint/commit/05cc9a7
Useful in order to discuss new checks of pylint 1.6.4 from [MQT](https://github.com/oca/maintainer-quality-tools)
Fix https://github.com/OCA/pylint-odoo/pull/70

[REF] requirements: Update version of pylint and astroid

---

pylint_odoo/checkers/modules_odoo.py

since these files are loaded only when running tests and in such a case your module and their external dependencies are installed.
Fix https://github.com/OCA/pylint-odoo/issues/74

[REF] missing-import-error: Skip test file

---

pylint_odoo/checkers/no_modules.py

To force a valid version of odoo in the manifest version.
Fix https://github.com/OCA/maintainer-quality-tools/issues/366

[IMP] manifest-version-format: Add valid_odoo_versions parameter

---

pylint_odoo/checkers/modules_odoo.py

Updating libraries used from requirements.txt 
This libraries don't was detect them because are nested imported or not imported directly from odoo.
Example of library imported nested: [psutils](https://github.com/odoo/odoo/blob/8.0/requirements.txt#L20)
- [psutils with try except ImportError](https://github.com/odoo/odoo/blob/d81258ab8e0dcb6c0df3a47ab8084ec99b7d3e24/openerp/http.py#L40-L43)
Example of library not used: [pyparsing](https://github.com/odoo/odoo/blob/8.0/requirements.txt#L25)
- <img width="576" alt="screen shot 2016-10-14 at 7 41 07 am" src="https://cloud.githubusercontent.com/assets/6644187/19387700/89d92616-91e1-11e6-9b70-1b8857625232.png">
Fix https://github.com/OCA/maintainer-quality-tools/issues/374

[FIX] missing-import-error: Updating libraries

---

pylint_odoo/checkers/no_modules.py

Currently the regex allow any char instead of just dot, because the regex `r"\d+."` the dot is a standard of regex to any char.
```bash
>>> import re
>>> bool(re.match(r'\d+.\d+', '8,0'))
True
>>> bool(re.match(r'\d+\.\d+', '8,0'))
False
>>> bool(re.match(r'\d+\.\d+', '8.0'))
True
```
Thanks @lasley in the following comment: https://github.com/OCA/maintainer-quality-tools/pull/375#issuecomment-253862702

[FIX] manifest-version-format: Fix regex to use explicit dot instead of any char

---

pylint_odoo/checkers/no_modules.py

If you enable just `manifest-version-format` is not working.
Example: 
- `pylint --load-plugins=pylint_odoo -d all -e manifest-version-format module_with_bad_manifest_version` is not detected before of this fix.
After of this fix now is detected.

[FIX] manifest-version-format: Support -e manifest-version-format only

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/pylint_oca_broken.py

If you use call a `super` method then you will need return the original
value.
If you want overwrite a original method then you need add documentation
of why and add a `pylint: disable=missing-return`

[ADD] missing-return

---

.coveragerc
pylint_odoo/checkers/modules_odoo.py
pylint_odoo/misc.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/__openerp__.py
pylint_odoo/test_repo/broken_module/demo/duplicated_id_demo.xml

Fix OCA/pylint-odoo#83
Change test diff message in case of fails:

[REF] duplicate-xml-record-id: Get xml section from manifest to skip different origin

---

pylint_odoo/misc.py
pylint_odoo/test/main.py

- Now we have a `assertEqual(dict1, dict2)` then a sum of checkers is not required.
- `global VARIABLE` is not a good idea from unittest, because could affect the result of other tests.
- Convert comments to docstring
- Clean code

[FIX] test: Never use global into test

---

pylint_odoo/checkers/no_modules.py

Similar to https://github.com/OCA/pylint-odoo/pull/90
But for any type of value different to `string`

[FIX] method-NAME: Fix if value is not a string

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/model_view_odoo2.xml

Fix https://github.com/OCA/pylint-odoo/issues/76

[FIX] duplicate-xml-fields: False red using 2 tree sub-views *2M fields

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/no_odoo_module/__init__.py
pylint_odoo/test_repo/no_odoo_module/eval_used.py

**Detects referenced and inferred cases**
```
def func2(param): 
param("c = 2")
def func3():
my_dict = {
'my_eval': eval,  # [eval-referenced]
}
my_list = [eval]  # [eval-referenced]
my_var = eval  # [eval-referenced]
my_var('d = 3')  # [eval-referenced]
func2(eval)  # [eval-referenced]
return my_dict, my_list
```

[ADD] eval-referenced: Detects if a "eval" is referenced (without call it)

---

pylint_odoo/misc.py
pylint_odoo/test/main.py

pylint supports the following parameters:
- `--ignore=<file>[,<file>...]`
- `--ignore-patterns=<pattern>[,<pattern>...]`
But pylint-odoo is not using for ignore them from custom search files methods.
We are searching files: js, md, rst...
And we need skip them too if this parameters is defined.

[IMP] pylint-odoo: Adding support for parameters --ignore and --ignore-patterns

---

pylint_odoo/checkers/format.py

[FIX] Fix message of incoherent-interpreter-exec-perm
You have a python file with execution permissions but you don't have a interpreter magic comment.
If you really needs a execution permission then add a magic comment (1)
If you don't needs a execution permission then remove it with: chmod -x my_file.py
(1) https://en.wikipedia.org/wiki/Shebang_%28Unix%29
Referring to https://github.com/OCA/pylint-odoo/pull/1#issuecomment-269585616

[FIX] Fix message of incoherent-interpreter-exec-perm

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

Add check to detect deprecated/renamed parameters in a field constructor.
Checking the parameters specified in: https://github.com/odoo/odoo/blob/10.0/odoo/fields.py#L29

[ADD] renamed-field-parameter: detect deprecated field values (digits_compute, select) (#91)

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/test_module/except_pass.py

The `pass` into block except is not a good practice!
By including the `pass` we assume that our algorithm can continue to function after the exception occurred
If you really need to use the `pass` consider logging that exception
```python
try:
sentences
except:
pass
_logger.debug('Why the exception is safe....', exc_info=1))
```
fix https://github.com/OCA/maintainer-tools/pull/252

[ADD] except-pass: Emit message If a except:pass is used (OCA/#252)

---

pylint_odoo/checkers/format.py

[FIX] Skip incoherent-interpreter-exec-perm: Skip check for Windows

---

.travis.yml

Regression flake8 error because renamed of error from original tool
- https://github.com/OCA/pylint-odoo/pull/86/commits/e743df26c15ebadd865c2764856bff9dce78e14b

[REF] .travis.yml: Renamed flake8 error from F999 to F601

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test/main.py

Active xml-attribute-translatable if the version is 8.0
Referring to https://github.com/Vauxoo/pylint-odoo/pull/111

[FIX] xml-attribute-translatable: Skip if version is different 8.0

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

Improve the detection of possible SQL injection vectors by adding support for:
- executemany()
- queries built using the "+" operator
- queries built before the call to execute/executemany
Ignore queries built with private attributes (e.g.: self._table).

[IMP] sql-injection: support new cases and ignore some false positives

---

pylint_odoo/examples/.jslintrc

Fix https://github.com/OCA/pylint-odoo/issues/126
More info about: http://eslint.org/docs/rules/no-comma-dangle

[REF] jslint: Enable no-comma-dangle check

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

Avoid false messages if a variable `fields` is used from other side different to assign new columns for odoo classes
Referring to https://github.com/Vauxoo/pylint-odoo/issues/52

[FIX] fields: Validate a assign directly from root class

---

pylint_odoo/examples/.jslintrc

The ecmaFeatures waas deprecated for 2.0.0 version
More info about:
http://eslint.org/docs/user-guide/migrating-to-2.0.0#language-options
This FIX the following error: `ESLint configuration is invalid: - Unexpected top-level property "ecmaFeatures".` for recent builds: https://travis-ci.org/OCA/pylint-odoo/jobs/242118234#L633

[FIX] jslintrc: Remove deprecated ecmaFeatures key

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/__openerp__.py
pylint_odoo/test_repo/broken_module2/__openerp__.py
pylint_odoo/test_repo/broken_module3/__openerp__.py
requirements.txt

This modification validate the website key into the manifest file using the `rfc3986` library
If the website contains `,` is considered a url bad formatted
Fix https://github.com/OCA/pylint-odoo/issues/121

[ADD] website-manifest-key-not-valid-uri: For validate if the website into manifest is valid URI

---

pylint_odoo/misc.py
pylint_odoo/test_repo/broken_module/__openerp__.py
pylint_odoo/test_repo/broken_module/skip_xml_check.xml
pylint_odoo/test_repo/broken_module/skip_xml_check_2.xml
pylint_odoo/test_repo/broken_module/skip_xml_check_3.xml

This PR adding the functionality to skip xml resource like `pylint: disable=CHECK` the `CHECK` should be the name of the check, is not supported the number of the pylint check
This functionality only support `xml` files, one example of use is 
```xml
<?xml version="1.0" encoding="utf-8"?>
<odoo>
<data>
...
</data>
</odoo>
```
Fix https://github.com/OCA/pylint-odoo/issues/132

[IMP] pylint_odoo: Skip pylint check on one xml file

---

pylint_odoo/misc.py

Clean [TODO comment](https://github.com/OCA/pylint-odoo/blob/128d018791d2e74b6fbd9c5db19b0024c7f9e92b/pylint_odoo/misc.py#L99)
Currently if we have a big python project using pylint-odoo (non odoo module) is too slow because try get all files of the project.

[REF] cache: Cache other extension files just if is a odoo module

---

.gitignore
pylint_odoo/checkers/modules_odoo.py

For instance, README with .rst, .md or .txt extensions
These filenames are supported by Odoo when loading module info
_**ref:**_
`load_information_from_description_file():`
https://github.com/odoo/odoo/blob/e6863851/odoo/modules/module.py#L337
https://github.com/odoo/odoo/blob/e6863851/odoo/modules/module.py#L28

[IMP] missing-readme: Check for other supported file names

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test_repo/broken_module/pylint_oca_broken.py

Demo case, when _pylint-odoo_ is run on [OCA/website/website_seo_redirection](https://github.com/OCA/website/tree/cc382d3ccef0e550f06feb5ed580a627381e72f7/website_seo_redirection):
```
...
************* Module website_seo_redirection.models.website                                                            
W: 12, 4: Missing `return` (`super` is used) in method enumerate_pages. (missing-return)                               
...
```
However, `enumerate_pages()` is a generator, and [`super()` is called and its values are yielded](https://github.com/OCA/website/blob/cc382d3ccef0e550f06feb5ed580a627381e72f7/website_seo_redirection/models/website.py#L29-L34).
This PR adds a check if the function is a generator when `super()` is called and `return` is missing in the function.

[IMP] missing-return: Skip missing return if function is a generator

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/demo/duplicated_id_demo.xml
pylint_odoo/test_repo/broken_module/model_view2.xml
pylint_odoo/test_repo/broken_module/model_view_odoo.xml
pylint_odoo/test_repo/broken_module/model_view_odoo2.xml

Implements check for deprecated XML `<tree>` node attributes (`colors`, `fonts` and `string`) as stated in #146.

[ADD] xml-deprecated-tree-attribute: Implements check for deprecated tree attributes

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module3/__openerp__.py

This adds `$` to the end of default manifest version format to disallow versions like `10.0.1.0.0WHATEVER`.
Related: #152

[FIX] manifest-version-format: Adds matching for string end to default manifest version format

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test_repo/broken_module/tests/xml_not_important_3.xml
pylint_odoo/test_repo/broken_module/tests/xml_not_important_4.xml

Detect the children inside the odoo xml tag and only active the check `deprecated-data-xml-node` when exist one tag `data` inside de xml
This fix skip the follow case
```xml
<odoo>
<data noupdate="1">
<record></record>
</data>
<record></record>
</odoo>
```
I run this change over the module of odoo [sales_team](https://github.com/odoo/odoo/tree/saas-17/addons/sales_team)
Without this change the output is the follow
The pylint-odoo detect four files
- [addons/sales_team/security/sales_team_security.xml](https://github.com/odoo/odoo/blob/ca496c21989d92b0e1d717faa4e834326188e546/addons/sales_team/security/sales_team_security.xml#L44-L49) **False positive**
- [addons/sales_team/views/crm_team_views.xml](https://github.com/odoo/odoo/blob/ca496c21989d92b0e1d717faa4e834326188e546/addons/sales_team …

[FIX] pylint_odoo: Detect the children inside the odoo xml

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/test_module/__openerp__.py
pylint_odoo/test_repo/test_module/website_templates.xml

This adds a check for use of deprecated QWeb directives `t-*-options` (`t-field-options`, `t-esc-options` and `t-raw-options`) which are [to be removed after v10](https://github.com/odoo/odoo/blob/8f99b24f6cb1ea70b371e2944ff36b75a6f9c80e/odoo/addons/base/ir/ir_qweb/ir_qweb.py#L155) and should be replaced with the `t-options` directive.
Currently, you only get a warning in the logs as the templates which use these directives are compiled, but [only in dev mode](https://github.com/odoo/odoo/blob/8f99b24f6cb1ea70b371e2944ff36b75a6f9c80e/odoo/addons/base/ir/ir_qweb/ir_qweb.py#L160-L161) (`--dev` CLI parameter).
I haven't found any usage of `t-raw-options` in Odoo or elsewhere on GitHub, however, it [is theoretically possible](https://github.com/odoo/odoo/blob/8f99b24f6cb1ea70b371e2944ff36b75a6 …

[ADD] xml-deprecated-qweb-directive: Implements check for deprecated QWeb directives

---

pylint_odoo/checkers/no_modules.py

- Add licence OEEL-1 into allowed-licence.
Can be useful is somebody create a custom module to extend an Enterprise module.

[ADD] Add licence-allowed: OEEL-1

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/test_module/website_templates.xml

This pull request check if the `<script src>` or `<link href>` contains the character `?` or `#`  and if this a valid absolute path
Fix https://github.com/OCA/pylint-odoo/issues/160#issuecomment-336995763

[ADD] character-not-valid-in-resource-link: To valid the character '?/#' into the in src/href

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/models/model_inhe1.py

Check if the package start with dot to skip because this package is absolute import
This change now detect when the import start with dot for example
```python
from .no_exists import package
```
If the import start with dot that import is not detect as external dependency 
Related with https://github.com/Vauxoo/pylint-odoo/pull/134
Fix https://github.com/OCA/pylint-odoo/issues/170

[FIX] pylint_odoo: Check if the package start with dot to skip

---

pylint_odoo/test/main.py

Change the number of the appearances of the check `unnecessary-utf8-coding-comment`
Because this pull request https://github.com/OCA/pylint-odoo/pull/171 adding another file with `# coding: utf-8`
https://github.com/OCA/pylint-odoo/blob/2f26b156629ac27f0d0d40db46438fa87ef29537/pylint_odoo/test_repo/broken_module/models/model_inhe1.py#L1-L3

[FIX] pylint_odoo: Change the number of the appearances of the check unnecessary-utf8-coding-comment

---

pylint_odoo/misc.py

When a check is found the method `add_message` is called with the number of the check `W7904` instead of the name of the check `deprecated-openerp-xml-node`
This change is necessary to used the new configuration `odoo_check_versions` like this:
```python
odoo_check_versions = {                                                     
'useless-attribute-non-translatable': {                                 
'min_odoo_version': '8.0',                                          
},                                                                                                                                                                                             
} 
```
Without this change the `odoo_check_versions` should be like this:
```python
odoo_check_versions = { …
```

[FIX] pylint_odoo: Use check-name instead of check-code for add_message method

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/model_view_odoo2.xml

The check `duplicate-xml-fields` skip the comprobation if the field is inside the `search` tab
For example 
```xml
<record model="ir.ui.view" id="view_ir_config_search">
<field name="model">ir.config_parameter</field>
<field name="arch" type="xml">
<search string="System Properties">
<field name="key_config" context="{'one': 'data'}"/>
<field name="key_config" context="{'two': 'data'}"/>
</search>
</field>
</record>
```
Fix https://github.com/OCA/pylint-odoo/issues/169

[FIX] pylint_odoo: The check duplicate-xml-fields skip if the field is inside the search tag

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

The check `translation-required` now detects the parameter `subject` and `body` into the method `message_post`, those parameter should be translatable
This change detect when the parameter `subject` and `body` not is translatable, one example like the follow
```python
self.message_post(subject='Subject not translatable',
body='Body not translatable')
```
This change detects many way to not translatable string
```python
'Subject not translatable'
'Body not translatable %s' % variable
'Subject not translatable %(value)s' % {'value': variable}
'Subject not translatable {}'.format(variable)
```
Fix https://github.com/OCA/pylint-odoo/issues/176

[REF] The method message_post need the subject and body be translatable

---

pylint_odoo/examples/.jslintrc

Right now this fails:
```js
var what = really ? "yes" : "no";
```
Ref: https://eslint.org/docs/rules/multiline-ternary
@Tecnativa

Allow short ternary expressions

---

.travis.yml

This change allows both formatting styles when a line break is around a
binary operator, to be before or after the operator. This is due to a
change in PEP-8 recomendations.
For more info, see the following MQT issue:
https://github.com/OCA/maintainer-quality-tools/issues/545

[REF] .travis.yml: Allow both W503 and W504 formats

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

This change causes the lint translation-required to take into account
certain cases which were triggering false positives, like the following:
`self.message_post(body=_('error: %s') % error_code)`
i.e. tose messages involving variables in the message string.
In addition, this adds some cases to the tests, to ensure they work as
expected.
Closes #187

[FIX] translation-required: Fix some false positives

---

pylint_odoo/checkers/no_modules.py

The return of the _register_hook method is never used, this is the
calling code in the loading phase:
```
env = api.Environment(cr, SUPERUSER_ID, {})
for model in env.values():
model._register_hook()
```
It is then no customary and useless to return something.

Add _register_hook in "no missing return" methods

---

README.rst

Adding documentation to the way to skip one check based on the Odoo Version using the `odoo_check_versions` variable
If you need to valid one check using the Odoo version you should be used the
new variable ``odoo_check_versions``
For example, if you have one new check `your-new-check` and you need run only
if the Odoo version is between 9.0 and 11.0, inside the class you should be
declare the follow :
```python
...
class FormatChecker(PylintOdooTokenChecker):
...
odoo_check_versions = {
'your-new-check': {
'min_odoo_version': '9.0',
'max_odoo_version': '10.0',
}
}
...
```

[DOC] README.rst: Adding documentation to the way to skip one check based on the Odoo Version

---

requirements.txt

It happens that some files use `six` library, but that library is not in `requirements.txt` file. Thus, this PR fixes that.

[FIX] Include six in requirements.txt

---

pylint_odoo/misc.py
pylint_odoo/test/main.py

Currently, the parameter --valid_odoo_versions is being ignored when
checking a module's version in its manifest. So, for example, if the
only valid version is 11.0, and a module has in its manifest
`10.0.1.0.0`, this lint wouldn't be triggered, resulting in a false
negative.
This commit ensures the above parameter is taken into account when
checking module versions set in the manifest.
A new test case is provided for this behavior

[FIX] manifest-version-format: Don't ignore valid Odoo versions

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test_repo/eleven_module/migrations/11.0.1.0.0/not_used_from_manifest.xml

If there are data files into the "migrations" directory, e.g. XML/CSV,
they are probably intended to be used by the migration script, hence
they  won't be referenced from the manifest.
This commit causes the lint to ignore files located into the
"migrations" directory.
Closes https://github.com/OCA/pylint-odoo/issues/212

[IMP] file-not-used: Ignore unused files into the migrations directory

---

pylint_odoo/examples/.jslintrc
pylint_odoo/test/main.py

This relaxation comes from the fact that sometimes you're extending another object, and thus you don't need to reexplain everything if it is explained in the parent class.
A common coding pattern is:
```js
return this._super.apply(this, arguments);
```
In such cases, it should be enough to declare the return type, since further descriptions should be found in the upstream class.
Another common pattern is reusing upstream parameters, or using parameters with names that are specific enough so as to not require a description, so the requirement of param description is relaxed here too.
- Disable inline block spacing.
- Require multiline dangling commas.
- Enforce PEP8-like line limits.
- Require spaces before comments.
- Requre `"use strict"`.
---
@Tecnativa

Jslint jsdoc relax

---

pylint_odoo/examples/.jslintrc

ES3 doesn't matter today, so this rule makes no sense.
@Tecnativa

Allow usage of `undefined`

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test/main.py

This check is deprecated since:
- https://github.com/odoo/odoo/commit/8226aa1db828d2a559c7ffaa31a27ef3e5ba4d0b
Fix https://github.com/OCA/pylint-odoo/issues/222
cc @pedrobaeza @Yajo

[REF] missing-import-error: Check enabled just for odoo <= 11.0

---

pylint_odoo/examples/.jslintrc

@Yajo where did you encouter problems with this? I tested with my python2 and 3 installation, and both nicely give me nothing if there's no jsdoc, and an error if I fill in a wrong one. That's what we want, right?

[DEL] require-jsdoc, keep require-valid-jsdoc

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py

Fix https://github.com/OCA/pylint-odoo/issues/232
cc @lmignon

[REF] manifest-required-authors: Support old deprecated parameter

---

.travis.yml
pylint_odoo/checkers/modules_odoo.py
pylint_odoo/checkers/no_modules.py
pylint_odoo/misc.py
pylint_odoo/test/main.py
requirements.txt
tox.ini

* Old classes were removed for new versions and 1.9 is using a dual compatibility.:
- https://github.com/PyCQA/astroid/blob/eaef0dbedb32ea9540505db6450454b5e8dbd10b/astroid/node_classes.py#L4261-L4267
* Remove python-lxml apt package since that new lxml is using wheels and travis is using pip cache
* Update compatibility with py3.7
* Use a dummy pylint configuration file in order to avoid using the default one from the HOME (Useful for local testing)
* pylint2 is not compatible with python<3 anymore so removing that cases from tox and travis
* pylint2 renamed `check_message_id` to `get_message_definition` in:
- https://github.com/PyCQA/pylint/commit/5ccbf9eaa54c0c302c9180bdfb745566c16e416d

[REF] tox: Upgrade new pylint for py3

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py

Since that new version of pylint is not considering a check for
"print()" in python3

[ADD] print-used: Use _logger instead of print

---

pylint_odoo/examples/.jslintrc
pylint_odoo/test/main.py

These are required in Odoo in order to mark a tour as failed manually.
It can also be helpful to log some interesting details for developers that shouldn't matter for users. Odoo uses it, in fact.
See https://github.com/OCA/website/pull/627#discussion_r285006941 where this was discovered.

Allow console statements

---

.travis.yml
tox.ini

Currently, travis is red...
This PR allow us to debug from travis build if eslint was installed correctly.
Fix related for MQT: https://github.com/OCA/maintainer-quality-tools/pull/607

[FIX] .travis.yml: Upgrade nvm version supported for eslint

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

For the same intantion behind search, compute, inverse naming convention
also alert on the same level for default. As being an indirectly called
method, too, this enables better static conde analysis.

[ADD] method-default prefix

---

.travis.yml
pylint_odoo/checkers/no_modules.py
pylint_odoo/misc.py
pylint_odoo/test/main.py
tox.ini

Odoo version 13.0 is coming soon
TODO:
Fixing missing unnecessary-utf8-coding-comment:
- `pylint_odoo/test_repo/broken_module3/__init__.py:1: [C8202(unnecessary-utf8-coding-comment), ] UTF-8 coding is not necessary`
NOTE: Testing locally using
`python3.7 -m pylint --load-plugins=pylint_odoo -d all -e unnecessary-utf8-coding-comment pylint_odoo/test_repo/broken_module3/__init__.py`
UPDATE:
The TODO will be worked from:
- https://github.com/OCA/pylint-odoo/issues/252

[REF] pylint_odoo: Supports odoo 13.0

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

This reverts commit 586c6819539a57aae847748e47518ffd757ecc7d.
From pull request https://github.com/OCA/pylint-odoo/pull/250
In order to fix https://github.com/OCA/pylint-odoo/issues/253
and work better this new check.

Revert "[ADD] method-default prefix"

---

pylint_odoo/checkers/modules_odoo.py

cc @eilst 
FIX https://github.com/OCA/pylint-odoo/issues/262

[FIX] rst-syntax-error: Using a 0 by default if line None is returned

---

pylint_odoo/checkers/modules_odoo.py

The checker uses 'isort' to know if an imported library is in the
standard library or is a third party library. Then, for third party
libraries, the check will fail if it is not declared in the addon
manifest's external dependencies.
Some python modules are known to be used by Odoo and do not need to
be declared in the external dependencies. These libraries are listed
in a whitelist of the checker.
isort's SortImports class is initialized with an argument
'known_standard_library' where the whitelist is passed. It forces
isort to consider them as standard library, thus ignoring the check.
However, when the project's directory contains an '.isort.cfg' file,
because the project uses isort to actually sort the imports in the code,
the file usually contains a line such as:
[settings] …

Fix incompatibility with isort configuration file

---

.travis.yml

Since that https://docs.travis-ci.com/user/languages/python/#specifying-python-versions is updated to use 3.7

[REF] .travis.yml: Using py3.7 stable instead of dev

---

pylint_odoo/misc.py

In order to avoid errors using a clean environment without codecs configured.
It is fixing 
```bash
File "/root/.cache/pre-commit/repov9q9gh9a/py_env-python3/bin/pylint", line 8, in <module>
sys.exit(run_pylint())
File "/root/.cache/pre-commit/repov9q9gh9a/py_env-python3/lib/python3.6/site-packages/pylint/__init__.py", line 20, in run_pylint
Run(sys.argv[1:])
File "/root/.cache/pre-commit/repov9q9gh9a/py_env-python3/lib/python3.6/site-packages/pylint/lint.py", line 1628, in __init__
linter.check(args)
File "/root/.cache/pre-commit/repov9q9gh9a/py_env-python3/lib/python3.6/site-packages/pylint/lint.py", line 943, in check
self._do_check(files_or_modules)
File "/root/.cache/pre-commit/repov9q9gh9a/py_env-python3/lib/python3.6/site-packages/pylint/lint.py", …
```

[FIX] rst_lint: Using UTF-8 encoding by default

---

pylint_odoo/misc.py

Better way to check whether a path is a path of a subdirectoy of a Odoo module.
Before, '/a/b/cc/d' was considered as a subdirectoy of '/a/b/c' because `'/a/b/c' in '/a/b/cc/d' == True`.
Now:
```python
os.path.commonprefix(["/a/b/c", "/a/b/cc/d"]) == "/a/b"  # not a subdirectory
os.path.commonprefix(["/a/b/c", "/a/b/c/d"]) == "/a/b/c"  # subdirectory
```

[FIX] Visit module: manage odoo subdirectories

---

pylint_odoo/checkers/modules_odoo.py

The error "missing-manifest-dependency" is raised in an import if the module name in the import is not listed in the python external dependencies, in the __manifest__.py file. For example, in the following import statement, the module "dateutil" should be listed in the python external dependencies:
from dateutil.relativedelta import relativedelta
The verification for this is made checking if either the module name (in this case "dateutil.relativedelta") or the substring before the first dot ("dateutil") is in the python external dependencies and else it is raised the error "missing-manifest-dependency". The problem with this verification is the possibility of the module name contain dots in its original name. For example, in my case, I'm trying to do the following import:
from …

[ADD] Possibility of package name include dots

---

pylint_odoo/misc.py

Closes https://github.com/OCA/pylint-odoo/issues/282

[FIX] get_manifest_file: Get manifest file even if it is checking only one file and not the module like pre-commit uses

---

pylint_odoo/checkers/modules_odoo.py

Identified running:
- `PYTHONPATH=~/pylint-odoo python3 -m pylint -d all -e missing-import-error,missing-manifest-dependency --load-plugins=pylint_odoo addons/* odoo/addons/*`
- [PyPDF2](
https://github.com/odoo/odoo/blob/47707e1b099195487fd3d3e0ae012e4aed5a9bc5/requirements.txt#L33)
- [chardet](https://github.com/odoo/odoo/blob/47707e1b099195487fd3d3e0ae012e4aed5a9bc5/requirements.txt#L2)
- [urllib3 (requests dependency)](https://github.com/odoo/odoo/blob/47707e1b099195487fd3d3e0ae012e4aed5a9bc5/requirements.txt#L40)

[REF] missing-import-error: Add new packages for Odoo v13.0

---

pylint_odoo/checkers/modules_odoo.py

Lately i had some travis fails due to openupgradelib is not in the external dependencies, i don't know if we should add it to all the modules that contains migration or we can add it separately in the repositories, in isort.cfg
https://github.com/OCA/pylint-odoo/issues/247
or will work with the changes i did.
https://travis-ci.org/github/OCA/commission/jobs/707123086

[IMP] Add openupgradelib as a whitelist.

---

.gitignore
pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/i18n/broken_module.pot
pylint_odoo/test_repo/test_module/i18n/fr.po

Odoo translation entries require the following comment
'#. module: MODULE'
If there is missing this comment the following issue could be reproduced:
- https://github.com/odoo/odoo/pull/55083
But it is complex to detect where is the issue really.
This check helps to know where is the error.

[REF] po-msgstr-variables: Check if there is missing 'module:' comment

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test_repo/eleven_module/tests/test_model1.py

It is more correct to use absolute imports in tests. Tests are not truly constitutive of the module, they just happen to be stored inside the module. Usually, in Python libs, they're stored outside of the package. Importantly, using the absolute import proves that the addon we develop works as a library too.
Current behavior before PR: pylint-odoo warns about relative imports in tests/*
Desired behavior after PR is merged: pylint-odoo does not warn about relative imports in tests/*
Fix #297 

[12.0][REF] pylint-odoo: odoo-addons-relative-import does not apply in test dir

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module3/__openerp__.py

Maintainers key in manifest must be a list of strings, according to https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/oca_module_lifecycle_maintainer_role.rst.
Current behavior before PR: Maintainers key is not check
Desired behavior after PR is merged: Maintainers check working and validating if it is a list of strings.
Fix #200 

[ADD] pylint-odoo: add new check to maintainers key in manifest must be a list of str

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/model_view2.xml

Consider next case: 
```
<record id="crm_case_form_view_leads_form_inherit" model="ir.ui.view">
<field name="name">crm.lead.form.lead</field>
<field name="model">crm.lead</field>
<field name="inherit_id" ref="crm.crm_case_form_view_leads"/>
<field name="arch" type="xml">
<label for="contact_name" position="replace"/>
...
</field>
</record>
```
Part of code where replace is use is a label tag and pylint-odoo does not recognize it, however, Odoo convert this part of code in a xpath tag with replace attribute but in that point already passed lint.
Current behavior before PR: warnings of code like above not found.
Desired behavior after PR is merged: warnings of code like above found.
-- I confirm I have signed the CLA and read the PR …

[FIX] pylint-odoo: modify dangerous-view-replace-wo-priority to check all child tags with replace

---

pylint_odoo/misc.py

Add compatibility to Odoo v14.0.
Current behavior before PR:
Pylint-odoo does not compatible with v14.0. 
Desired behavior after PR is merged:
Pylint-odoo compatible with v14.0. 
Fix #311 

[FIX] add compatibility to v14.0

---

.travis.yml
requirements.txt

pip 20.3 introduced a new dependency resolver that disallows having conflicting dependencies in the same environment. https://pip.pypa.io/en/stable/user_guide/?highlight=resolver#changes-to-the-pip-dependency-resolver-in-20-3-2020
As pylint-odoo requires pylint==2.5.3 (for python 3), a dependency conflict is easily obtained when trying to install it along with pylint:
conflict caused by:
The user requested isort==4.3.21
pylint 2.6.0 depends on isort<6 and >=4.2.5
pylint-odoo 3.5.0 depends on isort==4.3.4
and
The user requested pylint 2.6.0
pylint-odoo 3.5.0 depends on pylint==2.5.3
This forces the use of an older pylint and isort version, which is not ideal.
Current behavior before PR:
All checks working correct way.
Desired behavior …

[FIX] requirements: update min version pylint and isort

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/__init__.py
pylint_odoo/test_repo/broken_module/tests/__init__.py
pylint_odoo/test_repo/broken_module/tests/test_model.py
pylint_odoo/test_repo/eleven_module/__init__.py

Currently, the `__init__.py` file in the root directory of an Odoo module may import the tests folder, e.g. https://github.com/OCA/server-tools/blob/cca5dffd0dec68e1aa4209a8747d4381a97efa89/ir_sequence_standard_default/__init__.py#L6
Current behavior before PR: 
Folder test imported in Odoo module does not check.
Desired behavior after PR is merged:
Folder test imported in Odoo module is check.
Fix #293 

[ADD] test-folder-imported: check if tests folder is imported in init file

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/misc.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

If you are using:
- `_("Your %s %s is shipping") % ("red", "car")`
Better using:
- `_("Your %(color)s %(item)s is shipping") % {"color": "red", "item": "car"}`
In order to allow other languages change the order
- e.g. in Spanish: `"Su %(item)s %(color)s está enviándose"`
Fix https://github.com/OCA/pylint-odoo/issues/303

[ADD] translation-positional-used: New check to valid the allow change the order of string formatting

---

pylint_odoo/checkers/modules_odoo.py

In python versions above 3.5, following error occurs when try to get `modname` from node.
`AttributeError: 'Import' object has no attribute 'modname'`
Current behavior before PR:
Error caused by try to get `modname` from node from `Import` object.
Desired behavior after PR is merged:
No errors shown when try to get `modname` from node.
Fix https://github.com/OCA/pylint-odoo/issues/318

[FIX] test-folder-imported: check if node has a modname as attribute

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/misc.py
requirements.txt

The following line of code:
- https://github.com/OCA/pylint-odoo/blob/1b9018e3884fceced0a06a1a19b29ffaffa5f701/requirements.txt#L8
is pinning the pylint version because it could raise red with newer versions but we need keep upgrading this version each period of time
There is a new release pylint-2.6.0 on Aug 21, 2020
Current behavior before PR:
pylint-odoo works correctly.
Desired behavior after PR is merged:
pylint-odoo works correctly with new pylint version.
Fix #319 

[REF] requirements: upgrade pylint version

---

requirements.txt

The library is needed for the setup, but it is not specified in requirements.
Its installation depends on setuptools' `easy_install`, which is unreliable: 
- https://docs.openstack.org/pbr/latest/#pbr-python-build-reasonableness 
- https://pip.pypa.io/en/latest/cli/pip_install/#controlling-setup-requires
Example of the error that might be caused: https://github.com/Tecnativa/doodba/runs/2314862208?check_suite_focus=true#step:7:1476
Pre-installing `pbr` with pip solves the issue, so it could be added to the `requirements.txt` to force the installation that way.
ping @Yajo

[FIX] Add pbr to requirements

---

pylint_odoo/checkers/modules_odoo.py

The `file-not-used` check reports false positives on Windows. This is because it checks the raw strings in the manifest (which always has forward slashes for separators) against file paths (which always have back slashes for separators on Windows). This PR resolves this issue.

[FIX] file-not-used: fix false positives on Windows

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

So redefining the string is a valid case.
For instance:
- parent_date = fields.Date(related="parent_id.date", string="parent date")
If a string is not specified, field will be "Date".
But I need the string to be "Parent Date"
Fix https://github.com/OCA/pylint-odoo/issues/332

[FIX] attribute-string-redundant: "string" of related field is taken from the referenced one

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

Fix https://github.com/OCA/pylint-odoo/issues/339
cc @voronind

[FIX] attribute-deprecated: Check only 'Model' class' attributes

---

README.rst
pylint_odoo/examples/.pylintrc

Pylint-odoo shoud come with example .pylintrc file one can copy to project and start using right away.
This file is taken from https://github.com/OCA/server-env/blob/13.0/.pylintrc

Add .pylintrc example

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/misc.py

Fix https://github.com/OCA/pylint-odoo/issues/331

[FIX] xml-syntax-error: Fix crash if a xml has syntax errors

---

pylint_odoo/misc.py
pylint_odoo/test/main.py

Fix https://github.com/OCA/pylint-odoo/issues/337

[FIX] pylint_odoo: Fix manifest_version_format option ignored

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

Ignore cases when you are using almost one parameter
It means you maybe are using a concatenation for valid concatenation but parameters for other cases
Ignore cases for private parameters and private methods too
It is a common way to use a valid "cr.execute" for Odoo views in newer
versions
Fix https://github.com/OCA/pylint-odoo/issues/334
It could depends of feedback from:
- https://github.com/odoo/odoo/pull/76185

[FIX] sql-injection: Fix false positives

---

pylint_odoo/augmentations/main.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/test_module/migrations/10.0.1.0.0/pre-migration.py

The following path:
- module/x.y.z/migrations/pre-migration.py
has a few false negatives
Considering that standard method is:
def migrate(cr, version):
- invalid-name (C0103) for module and argument name
- e.g. "pre-migration.py" instead of pre_migration.py
- e.g. "cr" for cursor
- unused-argument (W0613) for argument
- e.g. "version" for version of Odoo
They are valid since that Odoo has already defined as it
So supressing from augmentations
Fix https://github.com/OCA/pylint-odoo/issues/338

[REF] invalid-name, unused-argument: Suppress check for migrations path

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

More info about see docstring of the method:
- https://github.com/odoo/odoo/blob/ff3064258a320e4008b3fb52a149e6751ae1e7f5/odoo/models.py#L5086-L5105
Using
- `self.with_context({'key': 'value'})`
The original context is overridden
It should be:
- `self.with_context(**{'key': 'value'})`
- `self.with_context(key='value')`
If you need to override the full context only silent this check using:
- `self.with_context({'key': 'value'})  # pylint: disable=context-overridden`
In order to allow an explicit overridden
Requested by @yajo from:
- https://github.com/odoo/odoo/pull/36164

[ADD] context-overridden: Better using kwargs instead of dictionary

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

Using the following code:
queries = [
"SELECT id FROM res_partner",
"SELECT id FROM res_users",
]
for query in queries:
self.env.cr.execute(query)
The check sql-injection shows the following error:
- AttributeError: 'NoneType' object has no attribute 'parent'
So, Now it is validating if it is not None

[FIX] sql-injection: AttributeError: 'NoneType' object has no attribute 'parent'

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

* [REF] sql-injection: No sql-injection using constants
The following examples should not be considered as sql-injection:
self.env.cr.execute("SELECT * FROM %s" % 'table_constant')
self.env.cr.execute("SELECT * FROM {}".format('table_constant'))
self.env.cr.execute("SELECT * FROM %(table_variable)s" % {'table_variable': 'table_constant'})
Since that the constant is not possible to inject
* [FIX] sql-injection: AttributeError: 'NoneType' object has no attribute 'parent'
Using the following code:
queries = [
"SELECT id FROM res_partner",
"SELECT id FROM res_users",
]
for query in queries:
self.env.cr.execute(query)
The check sql-injection shows the following error:
- AttributeError: 'NoneType' object has no attribute 'parent'
So, Now it is validating if it is not None
* [FIX] sql-injection: …

[FIX] sql-injection: No sql-injection using constants and small fixes

---

requirements.txt

Update pylint version after fixing the following issue:
- https://github.com/PyCQA/pylint/issues/5096

[REVERT] requirements: Using pylint<2.11.0 because issue 5096

---

pylint_odoo/misc.py
pylint_odoo/test/main.py

pre-commit script is running file by file as:
- `pylint module/__init__.py module/migrations/pre-commit.py`
It is generating a corner-case where odoo manifest file variable is filled
and pre-commit is the main module and it was detecting as main odoo module
But it is not
Validating the name of node.file is `__init__.py`
we can be sure that it is related with the odoo main module
Fix https://github.com/OCA/pylint-odoo/issues/357

[FIX] OdooChecker: Discard migrations folder as odoo main module

---

requirements.txt

Travis builds on Python 2.7 break because `lazy-object-proxy` can't be installed. This should fix it.

[FIX] Pinned lazy-object-proxy for Python 2.7

---

pylint_odoo/test/main.py
requirements.txt

`git diff v2.11.1..v2.13.5`
```diff
diff --git a/ChangeLog b/ChangeLog
index c730dc5b..32c5122f 100644
--- a/ChangeLog
+++ b/ChangeLog
@@ -2,30 +2,1063 @@
Pylint's ChangeLog
------------------
-
-
-What's New in Pylint 2.12.0?
+What's New in Pylint 2.14.0?
============================
Release date: TBA
..
-  Put new features here and also in 'doc/whatsnew/2.12.rst'
+  Put new features here and also in 'doc/whatsnew/2.14.rst'
-What's New in Pylint 2.11.2?
+..
+  Insert your changelog randomly, it will reduce merge conflicts
+  (Ie. not necessarily at the end)
+
+
+What's New in Pylint 2.13.6?
============================
Release date: TBA
+What's New in Pylint 2.13.5?
+============================
+Release date: 2022-04-06
+
+* Fix false positive regression in 2.13.0 for …
```

[REF] requirements: Bump pylint package from 2.11.1 to 2.13.5 for py3.x

---

.pre-commit-hooks.yaml

It will allow to add in your pre-commit.yaml directly an entry for pylint_odoo instead of pylint
.pre-commit-config.yaml
- repo: https://github.com/OCA/pylint-odoo
rev: 5.0.5
hooks:
- id: pylint_odoo
You can get the current `rev` in the current tags:
- https://github.com/OCA/pylint-odoo/tags

[ADD] pre-commit-hooks: Add pylint_odoo hook directly to be used from pre-commit.yaml directly

---

README.rst

Travis had changed the URL from travis-ci.org to travis-ci.com
This change uses the latest value

[REF] README: Use new travis URL

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

Calling external request needs to use timeout in order to avoid waiting for a long time
It could be even worse if you have one or many records locked
then calling a requests it could accumulate a lot of locks and
the workers could be used for more time and the system could be down
waiting for release
You can define your custom methods using the parameter: --external_request_timeout_methods
The default methods are:
- http.client.HTTPConnection
- http.client.HTTPSConnection
- odoo.addons.iap.models.iap.jsonrpc
- requests.delete
- requests.get
- requests.head
- requests.options
- requests.patch
- requests.post
- requests.put
- requests.request
- serial.Serial
- smtplib.SMTP
- suds.client.Client

[ADD] requests-without-timeout: It could wait for a long time

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module2/__init__.py

The original PR:
- https://github.com/OCA/pylint-odoo/pull/310
Talks about the following case:
- https://github.com/OCA/server-tools/blob/cca5dffd0dec68e1aa4209a8747d4381a97efa89/ir_sequence_standard_default/__init__.py#L6
It is using "from . import tests"
But this case of use was not used in the unittest
So, it is not detecting this common case

[IMP] test-folder-imported: Consider 'from . import test' missing case

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/i18n/es.po

Odoo raises error if the msgid is duplicated even if there are not models entries not duplicated
So, it is considering these kind of cases in order to match with Odoo errors but raising from CI early with static checker
Original PR:
- https://github.com/OCA/pylint-odoo/pull/290

[IMP] duplicate-po-message-definition: Detecting duplicated only with msgid

---

pylint_odoo/checkers/modules_odoo.py

The `xlrd` package is in Odoo's requirements since v10 [1].
[1] https://github.com/odoo/odoo/commit/0ac303d12ff0

[FIX] missing-import-error: add xlrd to whitelist

---

pylint_odoo/checkers/format.py
pylint_odoo/checkers/modules_odoo.py
pylint_odoo/checkers/no_modules.py

Reverts OCA/pylint-odoo#376
Old lints are failing, check the following PR:
- https://github.com/OCA/pylint-odoo/pull/385
But the old ones will be deleted soon since that we are planing to deprecate old odoo versions, py2 and use pre-commit hooks instead of pylint-odoo custom checks
So, we are reverting this PR in order to improve it in the new pylint-odoo version to avoid dedicating time to deprecated checks

Revert "[PERF] Checkers only run when enabled #372"

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py
pylint_odoo/test_repo/broken_module/models/broken_model.py

It is better using timeout for this method too as documentation says:
- https://docs.python.org/es/3/library/ftplib.html#ftplib.FTP_TLS

[REF] external-request-timeout: Add ftplib.FTP method

---

pylint_odoo/checkers/no_modules.py
pylint_odoo/test/main.py

This allows to have titles in different case.
For example this field declaration is not going to set a W8113:
```
has_changes_pending_approval = fields.Boolean(
string="Has changes pending approval"
)
```
But if we define the field in this way it will set a W8113:
```
has_changes_pending_approval = fields.Boolean(
string="Has Changes Pending Approval"
)
```
Fixes #387

[FIX] Only adds W8113 when field string is the same as title() format

---

README.md
tox.ini

tox was using a custom coverage file output in order to be able to run with parallels
But codecov needs to know this file
For now, commenting the parallels option and support no files to combine without errors

[REF] codecov: Enable codecov again

---

src/pylint_odoo/checkers/odoo_addons.py
tests/test_main.py

The check eval-referenced is heavy to compute since it needs to check
the inferred node for each variable name
eval-used will detect almost of case using this way
eval-referenced detected the following cases:
my_var = eval
eval-used is only detecting the following cases:
eval("...")
So, they are less cases but without heavy process
Running the following command:
- `py-spy record -o /tmp/py_spy.svg --threads --subprocesses -r 89 -- pytest -k test_20_expected_errors`
The heavy process in the profiler result is:
- https://github.com/OCA/pylint-odoo/blob/e0c9b25d4d8df55ad716862545f8339d297c8d7f/src/pylint_odoo/checkers/odoo_addons.py#L1120
- <img width="595" alt="Screen Shot 2022-10-23 at 10 35 16" src="https://user-images.githubusercontent.com/6644187/197401337-a788ffc2-b508-4493-bbb1-7a0449b …

[REM] eval-referenced: Replaced by eval-used check from pylint

---

src/pylint_odoo/checkers/odoo_addons.py

infer in nodes is a heavy process
It was reduced using only infer for cases where the name of the method is 'print' early
Running the following command:
- ` py-spy record -o /tmp/py_spy.svg --threads --subprocesses -r 89 -- pytest -k test_20_expected_errors`
The result is:
- https://github.com/OCA/pylint-odoo/blob/094873f526781cd2384fd338722b453ffc6fc0d5/src/pylint_odoo/checkers/odoo_addons.py#L719
- <img width="887" alt="Screen Shot 2022-10-23 at 10 48 31" src="https://user-images.githubusercontent.com/6644187/197402003-c459b5dd-99e1-4dc9-946a-2a70659535e6.png">

[IMP] print-used: Speed-up 'print-used' check avoid inferring

---

src/pylint_odoo/checkers/odoo_addons.py
testing/resources/test_repo/broken_module/models/broken_model.py
testing/resources/test_repo/broken_module/pylint_oca_broken.py
tests/test_main.py

Odoo v16.0 shows the following message:
- https://github.com/odoo/odoo/blob/9ba78dad0ccfda3ec955a39cba1b01e35605923a/odoo/exceptions.py#L131
So, this check is still vigent but for odoo instead of openerp
* Change "openerp" import references to "odoo"

[REF] openerp-exception-warning: Change to odoo-exception-warning

---

tests/test_main.py

We don't need it and we are not using it
Remove of the tests the following message:
```txt
-------------------------------------------------------------------
Your code has been rated at 7.14/10 (previous run: 10.00/10, -2.86)
```

[REF] tests: Remove 'score'

---

src/pylint_odoo/checkers/odoo_addons.py
tests/test_main.py

Running the following command:
- `pylint -d all -e invalid-name testing/resources/test_repo/broken_module/pylint_oca_broken.py`
The output is the following:
- `testing/resources/test_repo/broken_module/pylint_oca_broken.py:16: [C0103(invalid-name), snake_case] Class name "snake_case" doesn't conform to PascalCase naming style`
It requires the following pylint.cfg entry:
```cfg
[BASIC]
class-naming-style=PascalCase
```

[REM] class-camelcase: Replaced by invalid-name

---

setup.cfg

pylint dependency has the following requires-python:
- [>=3.7.2](https://github.com/PyCQA/pylint/blob/d591cce71cd06b01c5e94ded1a10c6c0fc092d6d/pyproject.toml#L34)
Related to https://github.com/OCA/pylint-odoo/issues/416

[REF] setup: Match requires-python = ">=3.7.2" from pylint

---

pylint_odoo/checkers/modules_odoo.py
pylint_odoo/test_repo/broken_module/model_view_odoo2.xml

Related to https://github.com/odoo/odoo/pull/103743
Fix https://github.com/OCA/odoo-pre-commit-hooks/issues/10
Backport of https://github.com/OCA/odoo-pre-commit-hooks/pull/32 to pylint-odoo@7.0

7.0 - [REF] checks_odoo_module_xml: Allow duplicated fields with 'groups'

---

README.md
src/pylint_odoo/checkers/custom_logging.py
src/pylint_odoo/checkers/odoo_addons.py
src/pylint_odoo/checkers/odoo_base_checker.py
src/pylint_odoo/checkers/vim_comment.py
testing/resources/test_repo/broken_module/models/broken_model.py
tests/test_main.py

Checks valid only for odoo >= 14.0
translation-format-interpolation
translation-format-truncated
translation-fstring-interpolation
translation-not-lazy
translation-too-few-args
translation-too-many-args
translation-unsupported-format
Checks valid only for odoo <= 13.0
translation-contains-variable
The odoo._ method changed from <=13.0 to >=14.0
<=13.0 is not using arguments:
- https://github.com/odoo/odoo/blob/a03aa23461498bba67/odoo/tools/translate.py#L447
>=14.0 is using arguments:
- https://github.com/odoo/odoo/blob/6a6e5f92789e1c/odoo/tools/translate.py#L446
So, the checks needs to be compatible with each odoo version related
To know what is the current version of the odoo analyzed is needed to use `pylint --valid_odoo_versions=13.0` option
Related to …

[REF] pylint_odoo: Process max_odoo_version and min_odoo_version for checks

---

src/pylint_odoo/checkers/odoo_addons.py
tests/test_main.py

The standard for options is using "-" to be used from cli parameters
even if the configuration file is used with underscore

[REF] pylint_odoo: Replace options name from "_" to "-"

---

src/pylint_odoo/checkers/odoo_base_checker.py
src/pylint_odoo/misc.py

It is not a built-in package for py3.10
In fact, it requires install this extra package
Better removing this extra requirement
NOTE: The weird part is that the tox environment is not raising the error, maybe the test-requirements is installing it

[FIX] pylint_odoo: "ImportError: No module named 'packaging'"

---

src/pylint_odoo/checkers/custom_logging.py

If you use the operator `-`
e.g. `datetime.now() - timedelta(days=1)`
The new code is replaced using: `datetime.now( % timedelta(days=3))` raising errors
Better using the same operator `datetime.now( - timedelta(days=3))`

[FIX] pylint_odoo: Using "node.op" instead of hardcoded %

---

src/pylint_odoo/checkers/custom_logging.py

binop are related to `-`, `+`, `%` but we are using only `%` to parse strings

[FIX] custom_logging: Fix AstroidSyntaxError using only binop related to '%'

---

src/pylint_odoo/checkers/odoo_addons.py
testing/resources/test_repo/broken_module/models/broken_model.py

Odoo is using TrasientModels for "res.config*" inherited classes from models directory

[REF] no-wizard-in-models: Add exception for "res.config*" inherited classes

---

.pre-commit-config.yaml

Gitlab is no longer used for flake8, this fixes the CI so that the lint step no longer fails.

[FIX] Update flake8 repo for pre-commit hooks

---

.pre-commit-config.yaml

Fixing the following traceback for a new environment:
`python3.10 -m tox -e lint`
lint: commands[0]> pre-commit run --all-files --show-diff-on-failure --color=always
[INFO] Installing environment for https://github.com/PyCQA/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('~/.cache/pre-commit/repotkw2xyso/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
Processing ~/.cache/pre-commit/repotkw2xyso
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing metadata (pyproject.toml): started …

[FIX] pre-commit-vauxoo: Fix isort hook - RuntimeError The Poetry configuration is invalid

---

README.md

Fixes #462.
The suggested usage was incorrect (wrong hook name) and may result 
in unnecessary issues for the repository and users alike.

[FIX] correct README pre-commit usage

---

README.md
src/pylint_odoo/checkers/odoo_addons.py
testing/resources/test_repo/test_module/res_partner_unlink.py
testing/resources/test_repo/test_module/sale_order_unlink.py
tests/test_main.py

Closes https://github.com/OCA/odoo-pre-commit-hooks/issues/73.
Context: https://github.com/odoo/odoo/commit/1c8a95809852baefa851985507a07ac7f6465dc7
Raising errors inside unlink(), especially when inherited can leave
stale data behind, therefore they are prohibited. This lint checks
for that.

[IMP] add new lint: no-raise-unlink

---

.github/workflows/test.yml

Each job now runs on a single job, makes it easier to read CI results. A big chunk of commented text that was not needed was also removed. actions/checkout has also been updated to v3 (v2 will be deprecated).
Closes #467.

[REF] ci: run only one tox env per job

---

README.md
src/pylint_odoo/checkers/odoo_addons.py
testing/resources/.pylintrc-odoo-deprecated-model-methods
testing/resources/test_repo/broken_module/models/broken_model.py
testing/resources/test_repo/eleven_module/models.py
tests/test_main.py

This new check looks for model methods that have been deprecated and should not be overriden in model classes. It takes into account odoo versions and comes with sane defaults which can be replaced by a custom list in the configuration file.
Closes #469.

[IMP] new `deprecated-odoo-model-method` check

---

setup.py

Commits which bump versions will no longer be displayed on the auto generated CHANGELOG.
Closes #471.

[REF] Filter out "bump version" from CHANGELOG

---

.github/workflows/test.yml
requirements.txt
setup.cfg
src/pylint_odoo/checkers/odoo_addons.py
tests/test_main.py
tox.ini

Pylint 3.0.0 has been released and with it a bunch of fixes and improvements. This repository has been updated to depend on this new version.
BREAKING CHANGE: Pylint 3.0.0 drops support for Python 3.7 so this plugin no longer supports Python 3.7 as well.
Closes #473.

[REF]: update to pylint 3.0.0, drop support for py3.7

---

src/pylint_odoo/checkers/odoo_addons.py
testing/resources/test_repo/test_module/migrations/10.0.1.0.0/pre-migration.py

Since migration files don't have an __init__,py, they can't perform relative imports, leaving absolute imports as the only option. Therefore this message does not apply to them.
Fixes #480.

[FIX] odoo-addons-relative-import: exclude migrations

---

src/pylint_odoo/checkers/odoo_addons.py
testing/resources/test_repo/broken_module/tests/test_model.py
tests/test_main.py

- Check for prohibited methods being overridden.
- Enables the user to specify, for example, core Odoo methods that should remain unaltered and cannot be overridden under any circumstances.
Please delete options that are not relevant.
1. There's a new test named `test_175_prohibited_method_override` within _test_main.py_.
2. Run the command below to start the test (using Python v3.9).
```sh
$ tox -e py39  -- -k test_175_prohibited_method_override
```
3. Verify that the test passes with two methods prohibited from being overridden. ✅ 
```sh
tests/test_main.py::MainTest::test_175_prohibited_method_override ************* Module broken_module.tests.test_model
testing/resources/test_repo/broken_module/tests/test_model.py:15 Prohibited override of "some_base_method_1" method. - …
```

[ADD] prohibited-method-override: Add a new check to identify methods marked as prohibited to override

---

README.md
src/pylint_odoo/checkers/odoo_addons.py

This PR updates the description of the `translation-positional-used` rule to clarify that it only applies when there are multiple positional arguments.
context: https://github.com/OCA/pylint-odoo/pull/305

[REF] readme: translation-positional-used (W8120) description

---

.coveragerc
MANIFEST.in
setup.cfg
tox.ini

When installing a wheel the file `<installroot>/requirements/requirements.txt` is created. This appears to have been intentionally introduced to fix #440 by introducing the following lines to `setup.cfg`:
- https://github.com/OCA/pylint-odoo/blob/6e857c52117ef8597e0433b32ca6fac302ea76b8/setup.cfg#L38-L40
However, this is not the correct format for adding files (they should be an array of `(path, file)` tuples), resulting in a directory called "/requirements" that will contain the file, likely not what we want.
It is unclear to me how source tarballs were being generated before, because requirements.txt should always be included when building with setuptools.
**To Reproduce**
Steps to reproduce the behavior:
```
$ python -m venv venv
$ source venv/bin/activate
$ pip install build installer …
```

[REM] pylint_odoo: Remove requirements/requirements.txt from build

---

src/pylint_odoo/checkers/odoo_addons.py

Reassign self.linter.config variables is not a good practice
Since that it could be used from other jobs and using a dirty value

[REF] pylint_odoo: Avoid reassigning self.linter.config

---

.github/workflows/test.yml

The coverage report are not uploading because and issue with old version

[REF] github: Updated codecov action version

---

README.md
src/pylint_odoo/checkers/custom_logging.py
src/pylint_odoo/checkers/odoo_addons.py
testing/resources/test_repo/broken_module/models/broken_model.py

Using the following code:
```python
"%s".lstrip() % "value"
```
`binop.left` is returning the structure different if the method is called `method("%s" % value)` and `"%s".method() % value`
So the code above is malformed `'%s'.lstrip( % 'value')`
Raising the following error:
```txt
File "site-packages/astroid/builder.py", line 181, in _data_build
node, parser_module = _parse_string(
^^^^^^^^^^^^^^
File "site-packages/astroid/builder.py", line 480, in _parse_string
parsed = parser_module.parse(
^^^^^^^^^^^^^^^^^^^^
File "site-packages/astroid/_ast.py", line 30, in parse
return ast.parse(string, type_comments=type_comments)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "python3.11/ast.py", line 50, in parse
return compile(source, filename, mode, …
```

[FIX] pylint_odoo: Fix AstroidSyntaxError

---

src/pylint_odoo/checkers/odoo_addons.py
testing/resources/test_repo/broken_module3/__manifest__.py

The following code:
- `{"key": "" or ""}`
It is parsed correctly the node code
But `ast.literal_eval` shows the following traceback:
```txt
Exception on node <Dict.dict l.3 at 0x10ef6aba0>
File "pylint/utils/ast_walker.py", line 91, in walk
callback(astroid)
~~~~~~~~^^^^^^^^^
File "pylint_odoo/checkers/odoo_addons.py", line 1034, in visit_dict
manifest_dict = ast.literal_eval(node.as_string())
File "3.13/lib/python3.13/ast.py", line 114, in literal_eval
return _convert(node_or_string)
File "3.13/lib/python3.13/ast.py", line 103, in _convert
return dict(zip(map(_convert, node.keys),
map(_convert, node.values)))
File "3.13/lib/python3.13/ast.py", line 113, in _convert
return _convert_signed_num(node)
File "3.13/lib/python3.13/ast.py", line 87, in …
```

[FIX] pylint_odoo: Fix parsing dictionary from manifest

---

.github/workflows/test.yml
requirements.txt
setup.cfg
tox.ini

pylint drops support for python3.8
Also, py3.8 stop official support recently
- `pylint.extensions.bad_builtin`
- `py_version` based on the odoo version matched to OS released and python version
- Rename the `[MASTER]` section to `[MAIN]`

[REF] pylint_odoo: Update pylint from v3.1 to v3.3 remove py38 support

---

tests/test_main.py

Before of this commit, if you add a "pdb" you can not see the pdb input because it is redirected
With this commit you are able to use pdb bypassing the redirect if sys.gettrace is enabled (pdb enabled)

[REF] tests: Support pdb to debug pylint checks

---

README.md
src/pylint_odoo/checkers/custom_logging.py
src/pylint_odoo/checkers/odoo_addons.py
src/pylint_odoo/misc.py
testing/resources/test_repo/broken_module/models/broken_model.py
tests/test_main.py

Related to https://github.com/odoo/odoo/pull/174844
The new way to translate is using `self.env._()` instead of `_` method
But if there is not environment available in the code you can use LazyTranslate
```python
from odoo. tools import LazyTranslate
_lt = LazyTranslate(__name__)
```
Based on https://github.com/OCA/pylint-odoo/pull/514
Closes #514

[ADD] prefer-env-translation: Add new check for odoo v18.0

---

README.md
requirements.txt
src/pylint_odoo/checkers/odoo_addons.py
src/pylint_odoo/misc.py
tests/test_main.py

[REF] website-manifest-key-not-valid-uri: Remove dependency to validators
Adding the same regex to validate URL
[REF] manifest-behind-migrations: Transform version to tuple without packaging library
Reduce the requirements because it is a simple code sustitution

[REF] website-manifest-key-not-valid-uri,manifest-behind-migrations: Remove dependencies to extra packages

---

src/pylint_odoo/checkers/odoo_addons.py
src/pylint_odoo/checkers/odoo_base_checker.py
src/pylint_odoo/misc.py
tests/test_main.py

If you use `--valid-odoo-versions="10.A"` notice there is not digit value
It will raise exceptions errors not watched
This commits catchs the errors

[FIX] manifest-version-format: Catch ValueError exception for valid-odoo-versions parameter

---

README.md
src/pylint_odoo/checkers/odoo_addons.py
testing/resources/test_repo/twelve_module/__manifest__.py
tests/test_main.py

This new check verifies that no external sources are referenced on modules' assets.
Related to: https://github.com/OCA/odoo-pre-commit-hooks/issues/124.

[IMP] add manifest-external-assets check

---

README.md
src/pylint_odoo/checkers/odoo_addons.py
testing/resources/test_repo/broken_module/models/broken_model.py
tests/test_main.py

Bad
```python
name = fields.Char(
compute=_compute_name,
search=_search_name,
inverse=_inverse_name,
)
```
Good
```python
name = fields.Char(
compute="_compute_name",
search="_search_name",
inverse="_inverse_name",
)
```
Fix https://github.com/OCA/odoo-pre-commit-hooks/issues/126

[ADD] string-method-name: Add string-method-name check to preserve inheritability

---

README.md
src/pylint_odoo/checkers/odoo_addons.py
testing/resources/test_repo/broken_module/models/broken_model.py

Fix the following case of code
```python
DOMAIN = "[]"
field1 = fields.Many2one("res.partner", domain=DOMAIN)
```
It is a valid case
So, only considering methods from classes used
```python
def _domain(self):
pass
field1 = fields.Many2one("res.partner", domain=_domain)
```

[FIX] inheritable-method-*: Consider only methods from classes

---

README.md
src/pylint_odoo/checkers/odoo_addons.py
testing/resources/test_repo/broken_module/models/broken_model.py
tests/test_main.py

Searching all records may impact performance.
It detects if the domain for "search" or "search_read" methods is empty
Discarding if it has "limit" or "count"

[ADD] no-search-all: No search with empty domain

---

README.md
src/pylint_odoo/checkers/odoo_addons.py

Odoo 18.0+ uses translation method `self.env._`
Older ones use translation method `_`
So the message is aligned to odoo version

[REF] translation-required: Use translation method based on the odoo version

---

README.md
src/pylint_odoo/checkers/odoo_addons.py
testing/resources/test_repo/twelve_module/models.py
tests/test_main.py

Detects mismatches between the current method
and the method called via super()
e.g.
def name_get(self):
return super().name_get2()
This rule ensures that `super()` calls always reference the same
method being defined, preventing mismatches

[ADD] super-method-mismatch: Check super() calls match current method

---

src/pylint_odoo/checkers/odoo_addons.py
testing/resources/test_repo/broken_module/tests/test_model.py

It is common generating a super calling the original method but defining a cache or queue method in order to support the feature correctly
So, it is a valid super-method-mismatch case
Now supported

[REF] super-method-mismatch: Consider queue and cache defined methods as valid
